version: "3"

services:
  mosquitto-1:
    image: eclipse-mosquitto:1.6.15-openssl
    volumes:
      - C:\mosquitto\config\mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - C:\mosquitto\data:/mosquitto/data 
      - C:\mosquitto\log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001


  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: wurstmeister/kafka:2.12-2.5.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: 'TEMPERATURE:1:1, MOVINGAVG:1:1, RESERVOIRSAMPLING:1:1'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  kafkaConnect:
    image: mongokafkaconnect:v1
    depends_on:
      - kafka
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9093'
      CONNECT_REST_ADVERTISED_HOST_NAME: kafkaConnect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR,com.mongodb.kafka=DEBUG"
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    

  mqttKafkaBridge:
    image: mqttkafkabridge:v1
    depends_on:
      - mosquitto-1
    ports:
      - 4444:4444

  temperatureSensor:
    image: temperaturesensor:v1
    depends_on:
      - mosquitto-1
    ports:
      - 7777:7777

  mongo:
    image: mongo
    ports:
      - 27017:27017  

  streamProcessing:
    image: streamprocessing:v1
    depends_on:
      - mongo
      - kafka
    ports:
      - 9432:9432